In [159]:
import numpy as np
import random as RD

CODE TESTING

In [194]:


epsilon = 0.1
epsilon_initial = 1.0
epsilon_final = 0.01
epsilon_decay = 0.99995 

reward = 1

# table
    # length = number of actions
    # height = complete number of states
    # cell = q value

# cell change
    # first step -> bellman equation
    # future steps -> optimality equation 

x = ((-1,0), (1,0), (0,-1), (0,1))
print(len(x))
qt = np.zeros((3,3,3,3,2,4))
#print(qt)
actions = [1,2,3,4]

            # actions   N        S       W       E
            # a-vals  (-1,0)    (1,0)   (0,-1)  (0,1)
            # qindex  [[ 0        1       2       3 ]]
            
            #qvals    [[ 1        3       5       2]]
            
            
"""greedy algorithm"""
if np.random.rand() < epsilon:
    print("I chose a random actoin")
    # random action
    action_chosen = RD.choice(actions)
    print(action_chosen)
    # apply bellman equation
    qtable = None
else:
    np.argmax(qtable)

print("qt state",qt[(0)])
r = np.random.rand()
display(r)

4
I chose a random actoin
4
qt state [[[[[0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]]]


  [[[0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]]]


  [[[0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]]]]



 [[[[0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]]]


  [[[0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]]]


  [[[0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]]]]



 [[[[0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]]]


  [[[0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]]

   [[0. 0. 0. 0.]
    [0. 0. 0. 0.]]]


  [[[0. 0. 0. 0.]
    [0. 0. 0.

0.9097639009470762

In [ ]:
class Grid:
    def __init__(self, grid_size):
        self.grid_rows = grid_size
        self.grid_cols = grid_size
        
        self.a = tuple()
        self.b = tuple()
        
        self.agent_position = () 
        # North South East West
        self.actions = [(-1,0), (1,0), (0,-1), (0,1)]
        self.agent_state = tuple()
        
        self.reward = 0
        
        self.episodes = 5
        self.epsilon = 0.1
        self.epsilon_initial = 1.0
        self.epsilon_final = 0.01
        self.epsilon_decay = 0.99995 
        
        self.goal_position = ()
        
        self.q_table = np.zeros((grid_size,grid_size,grid_size,grid_size,2,len(self.actions)))
        
        #Bellman Optimality
        self.R = self.reward
        self.Alpha = 0.1
        self.gamma = 0.95

    def make_grid(self) -> tuple:
        # Create a list of all coordinate tuples
        grid_world = [(x, y) for x in range(self.grid_rows) 
                             for y in range(self.grid_cols)]
        # Convert the list to a tuple
        grid_world = tuple(grid_world)
        print("grid world", grid_world)
        return grid_world
    
    def initialize_pickup_dropoff(self):
        all_possible_locations = [(x, y) for x in range(self.grid_cols) for y in range(self.grid_cols)]
        self.a = RD.choice(all_possible_locations)
        self.b = RD.choice(all_possible_locations)
        while self.a == self.b: # they are diff
            self.a = RD.choice(all_possible_locations)
            self.b = RD.choice(all_possible_locations)
        print("a and b", self.a, self.b)
        return self.a, self.b
    
    def initialize_agent_and_goal(self): # TODO: NOT TUPLE
        self.agent_position = RD.choice([self.a, self.b]) # agent at a or b
        
        if self.agent_position == self.a:
            self.goal_position = self.b
        else:
            self.goal_position = self.a
        print("agent", self.agent_position)
        print("goal", self.goal_position)
        
        return self.agent_position, self.goal_position # this accounts for mapping its position to grid
        
    def initialize_agent_actions(self):
        return self.actions
    
    def first_state_transition(self):
        state = self.agent_position
        next_state = self.agent_position
        reward = 0.1
        random_choice = ()
        new_pos = ()
        
        print("agent pos at t1", self.agent_position)
        decayer = np.random.rand()
        decayer
        print("random val to compare with epsilon", decayer)
        for i in range(3):
            #RANDOM
            if decayer > 0.9:
                random_choice = self.actions[RD.randint(0,3)]     
                print("random_choice", random_choice)
                new_pos = (self.agent_position[0] + random_choice[0],
                self.agent_position[1] + random_choice[1])
                next_state = new_pos
                print("agent pos at t2", new_pos)
              
                q_current = self.q_table[state[0], state[1], self.a[0], self.a[1], random_choice]
                print("q_current",q_current)
                # Get the max Q-value for the next state
                q_next_max = np.max(self.q_table[next_state[0], next_state[1], self.a[0], self.a[1], :])
                # Bellman Optimality Equation
                q_updated = q_current + self.Alpha * (reward + self.gamma * q_next_max - q_current)
                # Update Q-table
                q_updated = self.q_table[state[0], state[1], self.a[0], self.a[1], random_choice] 
                print("random update", q_updated)

                #TODO: the next step may be to 
                    # 1. insert the update q-values into the table
                    # 2. code a relation between the part of the q table being updated and the num of episodes.
            #1-epsilon
            else:
                print("using q table state:", self.q_table[(state)])
                q_current = self.q_table[state[0], state[1], self.a[0], self.a[1], self.actions[0]]
                print("q_current",q_current)
                # Get the max Q-value for the next state
                q_next_max = np.max(self.q_table[
                    next_state[0], next_state[1],
                    self.a[0], self.a[1], :
                ])
                print("q_next_max",q_next_max)
                # Bellman Optimality Equation
                q_updated = q_current + self.Alpha * (reward + self.gamma * q_next_max - q_current)
                # Update Q-table
                q_updated = self.q_table[state[0], state[1], self.a[0], self.a[1], self.actions[0]] 
                print("greedy update", q_updated)
                
                q_current = self.q_table[state[0], state[1], self.a[0], self.a[1], random_choice]
                print("q_current",q_current)
                # Get the max Q-value for the next state
                q_next_max = np.max(self.q_table[next_state[0], next_state[1], self.a[0], self.a[1], :])
                # Bellman Optimality Equation
                q_updated = q_current + self.Alpha * (reward + self.gamma * q_next_max - q_current)
                # Update Q-table
                q_updated = self.q_table[state[0], state[1], self.a[0], self.a[1], random_choice] 
                print("random update", q_updated)
         
    

                        # North  South   West    East
    #self.actions = ((-1,0), (1,0), (0,-1), (0,1))
    def get_neighbors(self):
        visible_cells = [(-1, -1), (-1, 0), (-1, 1),
                      ( 0, -1),          ( 0, 1),
                      ( 1, -1), ( 1, 0), ( 1, 1)]

        neighbors = []
        for dx, dy in visible_cells:
            nx, ny =  0 + dx, 0 + dy
            if 0 <= nx < self.grid_cols and 0 <= ny < self.grid_cols:
                neighbors.append((nx, ny))
        print("neighbors", neighbors)
        return neighbors

        # Step 1: agent takes a random action
            # gets a reward
        # Step 2: agent observes next adjacent cells
            # return all rewards in each cell
        # Step 3: 
        
        #When you get a reward, update not just the last action but all recent actions that led to it.

        # The weight of the update decays with time
        




        
        
prox = Grid(4)
prox.make_grid()
prox.initialize_pickup_dropoff()
prox.initialize_agent_and_goal()
prox.first_state_transition()


grid world ((0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3), (3, 0), (3, 1), (3, 2), (3, 3))
a and b (1, 1) (0, 2)
agent (1, 1)
goal (0, 2)
agent pos at t1 (1, 1)
random val to compare with epsilon 0.4198250680903727
using q table state: [[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]
q_current [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
q_next_max 0.0
greedy update [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


IndexError: tuple index out of range

In [ ]:

grid_row = 5
grid_col = 5
goal_coord_x = grid_row
goal_coord_y = grid_col
reached_goal = 2
moves = 4
q_table = (grid_row, grid_col, goal_coord_x, goal_coord_y, reached_goal, moves)
np.zeros(q_table)

array([[[[[[0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.]]],


         [[[0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.]]],


         [[[0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
           [0., 0., 0., 0.]]],


         [[[0., 0., 0., 0.],
           [0., 0., 0., 0.]],

          [[0., 0., 0., 0.],
     

## Hyperparameters

In [ ]:
max_steps = 25
n_episodes = 1000

gamma = 0.95
alpha = 0.1
# TODO: double check if this is enough for random action
epsilon = 0.1
epsilon_initial = 1.0
epsilon_final = 0.01
epsilon_decay = 0.99995 

