In [14]:
from IPython.display import Image
import random
import numpy as np


In [ ]:
class GridWorld:
    def __init__(self, n: int, m: int, learning_rate: int, gamma: int):
        self.grid = np.zeros([n, m])
        self.agent_position = ((0,0))
        self.possible_states = []
        self.q_matrix = np.random.rand(5,5)
        self.learning_rate = learning_rate
        self.gamma = gamma
        self.reward_matrix = [0.5, 0.2, 0.3, 0.7, 0.0]    
    
     
    def populate_agents(self, num_agents: set):
        pos = self.agent_position
        # init grid
        for i in range(num_agents):
            dx = random.randint(1,self.n)
            dy = random.randint(1, self.m)
            pos.add((dx, dy))
        return pos
    def generate_grid(self):
    # initialie for q(s',a') consider all 0's
    # research done on initializeing vals
        return self.grid

In [ ]:
class Agent:
    def __init__(self, actions: tuple):
        self.actions = actions
        
    def choose_action(self, state):
        # TODO: Policy f: State -> Actions
        state = [[]]
        new_state = (state[0][0] = action[0] for action in actions) if action == 0 retrun True else 0
        # we are increasing the num of grids by a factor of 5
        return new_state, Agent.choose_action()
   


'THIS SECTION CONCERNS Q-TABLES'

In [17]:
trial1 = GridWorld(5,5,0,0).getgrid()
print(trial1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
