Where is the actual learning?
## SARSA-Lambda (bridge btw SARSA and monte carlo)

### Req: Exponential Decay
$$
G​=(1−λ)\sum_{n=1}^{∞}​λ^{n−1}G_{t}^{(n)}​
$$




In [13]:
import numpy as np
import random as rand
import scipy

#new_q = current_q + learning_rate * (reward + gamma * max(next_state) - current_q)
'''
final_q_value = sum((state, action))

'''

'\nfinal_q_value = sum((state, action))\n\n'

### Q-Table

In [ ]:
grid = [
        [0,1,2],
        [5,6,7],
        [8,9,10]
        ]

# actions
N = (1,1)
S = (2,2)
E = (2,1)
W = (1,2)

total_cells = 9 # total states
total_actions = 4

# q-table (stage 0)
qt = np.zeros((total_cells, total_actions)) # returns:

'''
  Noth South East West
0  0              0
1     .
2  .     .
.          .
.             .
9 0                0
''' 
print(qt)
# table

# 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Q Returning

In [ ]:
# Q-return instantiated as a 10-step return
G = 0
gamma = 0.98
for i in range(10):
    G += (gamma ** i) * rewards[t + i]
G += (gamma ** 10) * Q[s_t10][a_t10]

### Run Episode

In [ ]:
def GridWorldSim(state, transition_pr, reward_v, ):
    total_transitions = [0,5,6,9,10]
    return 

reached_A = False

def reset():
    initial_state = (0,0)
    
agent_position = (1,1)
goal_position = (3,3)
reward_total = []

def get_agent_position():
    return agent_position

nest_location = (1,2)
def choose_action():
    # North South East West
    return rd.choice(((1,1), (2,2), (2,1), (1,2)))

def get_state():
    current_state = (1,1) # example position
    return current_state

def run_episode():
    num_episodes = 0
    for episode in range(num_episodes+1):   
        if (episode == 5000):
            print(episode, "episodes")
            return 1
        elif get_agent_position == goal_position:
            reached_A = True
            return 1
        else:
            max_steps = 25
            reset()
            number_of_steps = 1
            reward_per_episode =  1
            take_action = choose_action()
            while number_of_steps<= max_steps and (agent_position != nest_location or reached_A != True):  
                # Continue until reaching location B or too many steps   
                state = get_state()
                action = choose_action(state)
                reward = take_action(action)
                reward_per_episode += reward
                done = check_done()
                number_of_steps += 1
            reward_total.append(reward_per_episode)
        
